name: Node.js
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: npm version ${{ steps.get_version.outputs.version }}
      - name: Validate and extract release information
        id: release
        uses: manovotny/github-releases-for-automated-package-publishing-action@v2.0.1

      - name: Set node version and build
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - name: Publish version
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}
