name: Node.js
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: npm version ${{ steps.release.outputs.version }}
      - name: Set node version and build
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - name: Publish version
        run: yarn npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.npm_api_token }}
